[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 8888
  publish = ".next"
  framework = "nextjs"

[functions]
  included_files = ["server.js"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

